import type { ImageSourcePropType } from 'react-native';

// Auto-generated logo mapping for providers.
// Each key is the provider name as it appears in the app's providers table.

const logos: Record<string, ImageSourcePropType> = {
  '1Password': require('./1password_logo.png'),
  'Adobe Creative Cloud': require('./adobe_creative_cloud_adobe_logo.png'),
  'Adobe CC': require('./adobe_creative_cloud_adobe_logo.png'),
  'Adobe Firefly': require('./adobe_firefly_logo.png'),
  'Ahrefs': require('./ahrefs_logo.png'),
  'Amazon Music Unlimited': require('./amazon_music_unlimited_amazon_logo.png'),
  'Amazon Prime': require('./amazon_prime_amazon_logo.png'),
  'Prime Video': require('./prime_video_amazon_logo.png'),
  'Apple Arcade': require('./apple_arcade_apple_logo.png'),
  'Apple Developer': require('./apple_developer_apple_logo.png'),
  'Apple Fitness+': require('./apple_fitnessp_apple_logo.png'),
  'Apple Music': require('./apple_music_apple_logo.png'),
  'Apple News+': require('./apple_newsp_apple_logo.png'),
  'Apple One': require('./apple_one_apple_logo.png'),
  'Apple TV+': require('./apple_tvp_apple_logo.png'),
  'Artlist': require('./artlist_logo.png'),
  'Audible': require('./audible_amazon_logo.png'),
  'AWS': require('./aws_amazon_logo.png'),
  'Backblaze': require('./backblaze_logo.png'),
  'Bitwarden Premium': require('./bitwarden_premium_bitwarden_logo.png'),
  'Bloomberg': require('./bloomberg_logo.png'),
  'Bolt.new': require('./bolt.new_bolt_logo.png'),
  'Box': require('./box_logo.png'),
  'Brilliant': require('./brilliant_logo.png'),
  'Bumble': require('./bumble_logo.png'),
  'Calm': require('./calm_logo.png'),
  'Canva': require('./canva_logo.png'),
  'CapCut Pro': require('./capcut_pro_bytedance_logo.png'),
  'ChatGPT': require('./chatgpt_openai_logo.png'),
  'Chat GPT': require('./chatgpt_openai_logo.png'),
  'Claro Video': require('./claro_video_claro_logo.png'),
  'Claude': require('./claude_anthropic_logo.png'),
  'Cloudflare': require('./cloudflare_logo.png'),
  'Codecademy': require('./codecademy_logo.png'),
  'Coursera Plus': require('./coursera_plus_coursera_logo.png'),
  'Crunchyroll': require('./crunchyroll_logo.png'),
  'Cursor': require('./cursor_logo.png'),
  'DataCamp': require('./datacamp_logo.png'),
  'Datadog': require('./datadog_logo.png'),
  'DAZN': require('./dazn_logo.png'),
  'DeepL Pro': require('./deepl_pro_deepl_logo.png'),
  'Deezer': require('./deezer_logo.png'),
  'Descript': require('./descript_logo.png'),
  'DigitalOcean': require('./digitalocean_logo.png'),
  'Discord Nitro': require('./discord_nitro_discord_logo.png'),
  'Disney+': require('./disneyp_disney_logo.png'),
  'Docker': require('./docker_logo.png'),
  'Domestika Plus': require('./domestika_plus_domestika_logo.png'),
  'Dropbox': require('./dropbox_logo.png'),
  'Duolingo': require('./duolingo_logo.png'),
  'EA Play': require('./ea_play_ea_logo.png'),
  'ElevenLabs': require('./elevenlabs_logo.png'),
  'Envato Elements': require('./envato_elements_envato_logo.png'),
  'Envato': require('./envato_elements_envato_logo.png'),
  'Epidemic Sound': require('./epidemic_sound_logo.png'),
  'ESPN+': require('./espnp_espn_logo.png'),
  'Evernote': require('./evernote_logo.png'),
  'Expo EAS': require('./expo_eas_expo_logo.png'),
  'ExpressVPN': require('./expressvpn_logo.png'),
  'F1 TV': require('./f1_tv_f1_logo.png'),
  'Fastmail': require('./fastmail_logo.png'),
  'Figma': require('./figma_logo.png'),
  'Final Fantasy XIV': require('./final_fantasy_xiv_square_enix_logo.png'),
  'Financial Times': require('./financial_times_logo.png'),
  'Firebase': require('./firebase_google_logo.png'),
  'Fly.io': require('./fly.io_logo.png'),
  'Fortnite Crew': require('./fortnite_crew_epic_games_logo.png'),
  'Framer': require('./framer_logo.png'),
  'GeForce Now': require('./geforce_now_nvidia_logo.png'),
  'GitHub': require('./github_logo.png'),
  'GitHub Copilot': require('./github_copilot_github_logo.png'),
  'GitLab': require('./gitlab_logo.png'),
  'Google Cloud': require('./google_cloud_google_logo.png'),
  'Google Gemini': require('./google_gemini_google_logo.png'),
  'Gemini Advanced': require('./google_gemini_google_logo.png'),
  'Google One': require('./google_one_google_logo.png'),
  'Google Play Console': require('./google_play_console_google_logo.png'),
  'Google Workspace': require('./google_workspace_google_logo.png'),
  'Grammarly Pro': require('./grammarly_pro_grammarly_logo.png'),
  'Grok': require('./grok_xai_logo.png'),
  'HBO Max': require('./hbo_max_warner_bros._discovery_logo.png'),
  'Headspace': require('./headspace_logo.png'),
  'Heroku': require('./heroku_salesforce_logo.png'),
  'Hetzner Cloud': require('./hetzner_cloud_hetzner_logo.png'),
  'HeyGen': require('./heygen_logo.png'),
  'Higgsfield': require('./higgsfield_logo.png'),
  'HubSpot': require('./hubspot_logo.png'),
  'Hulu': require('./hulu_disney_logo.png'),
  'iCloud+': require('./icloudp_apple_logo.png'),
  'Ideogram': require('./ideogram_logo.png'),
  'IFTTT Pro': require('./ifttt_pro_ifttt_logo.png'),
  'Intercom': require('./intercom_logo.png'),
  'Jasper': require('./jasper_logo.png'),
  'JetBrains': require('./jetbrains_logo.png'),
  'Kindle Unlimited': require('./kindle_unlimited_amazon_logo.png'),
  'Krea': require('./krea_logo.png'),
  'Leonardo AI': require('./leonardo_ai_leonardo_logo.png'),
  'Linear': require('./linear_logo.png'),
  'LinkedIn Learning': require('./linkedin_learning_linkedin_logo.png'),
  'LinkedIn Premium': require('./linkedin_premium_linkedin_logo.png'),
  'Linktree Pro': require('./linktree_pro_linktree_logo.png'),
  'Lovable': require('./lovable_logo.png'),
  'Mailchimp': require('./mailchimp_logo.png'),
  'Make': require('./make_logo.png'),
  'MasterClass': require('./masterclass_logo.png'),
  'Medium': require('./medium_logo.png'),
  'MEGA': require('./mega_logo.png'),
  'Meli+': require('./melip_mercado_libre_logo.png'),
  'Meta Verified': require('./meta_verified_meta_logo.png'),
  'Microsoft 365': require('./microsoft_365_microsoft_logo.png'),
  'Microsoft Azure': require('./microsoft_azure_microsoft_logo.png'),
  'Midjourney': require('./midjourney_logo.png'),
  'Minecraft Realms': require('./minecraft_realms_mojang_logo.png'),
  'Mistral Le Chat': require('./mistral_le_chat_mistral_logo.png'),
  'Le Chat': require('./mistral_le_chat_mistral_logo.png'),
  'Movistar Play': require('./movistar_play_movistar_logo.png'),
  'MUBI': require('./mubi_logo.png'),
  'MyFitnessPal': require('./myfitnesspal_logo.png'),
  'n8n': require('./n8n_logo.png'),
  'NBA League Pass': require('./nba_league_pass_nba_logo.png'),
  'Neon': require('./neon_logo.png'),
  'Netflix': require('./netflix_logo.png'),
  'Netlify': require('./netlify_logo.png'),
  'New York Times': require('./new_york_times_logo.png'),
  'Nintendo Switch Online': require('./nintendo_switch_online_nintendo_logo.png'),
  'Noom': require('./noom_logo.png'),
  'NordVPN': require('./nordvpn_nord_security_logo.png'),
  'Notion': require('./notion_logo.png'),
  'OneDrive': require('./onedrive_microsoft_logo.png'),
  'OpusClip': require('./opusclip_logo.png'),
  'Otter.ai': require('./otter.ai_logo.png'),
  'Oura Ring': require('./oura_ring_oura_logo.png'),
  'Paramount+': require('./paramountp_paramount_logo.png'),
  'Patreon': require('./patreon_logo.png'),
  'pCloud': require('./pcloud_logo.png'),
  'Peacock': require('./peacock_nbcuniversal_logo.png'),
  'PedidosYa Plus': require('./pedidosya_plus_pedidosya_logo.png'),
  'Perplexity': require('./perplexity_logo.png'),
  'Personal Play': require('./personal_play_personal_logo.png'),
  'PlanetScale': require('./planetscale_logo.png'),
  'Platzi': require('./platzi_logo.png'),
  'PlayStation Plus': require('./playstation_plus_sony_logo.png'),
  'Poe': require('./poe_quora_logo.png'),
  'PostHog': require('./posthog_logo.png'),
  'Postman': require('./postman_logo.png'),
  'Proton Unlimited': require('./proton_unlimited_proton_logo.png'),
  'Proton VPN': require('./proton_vpn_proton_logo.png'),
  'Qobuz': require('./qobuz_logo.png'),
  'QuickBooks Online': require('./quickbooks_online_intuit_logo.png'),
  'Railway': require('./railway_logo.png'),
  'Rappi Pro': require('./rappi_pro_rappi_logo.png'),
  'Reddit Premium': require('./reddit_premium_reddit_logo.png'),
  'Render': require('./render_logo.png'),
  'Replit': require('./replit_logo.png'),
  'Resend': require('./resend_logo.png'),
  'Roblox Premium': require('./roblox_premium_roblox_logo.png'),
  'Rocket Money': require('./rocket_money_logo.png'),
  'Runway': require('./runway_logo.png'),
  'Salesforce': require('./salesforce_logo.png'),
  'Scribd': require('./scribd_logo.png'),
  'Semrush': require('./semrush_logo.png'),
  'Sentry': require('./sentry_logo.png'),
  'Shopify': require('./shopify_logo.png'),
  'Shutterstock': require('./shutterstock_logo.png'),
  'Skillshare': require('./skillshare_logo.png'),
  'Skool': require('./skool_logo.png'),
  'Slack': require('./slack_logo.png'),
  'Snapchat+': require('./snapchatp_snap_logo.png'),
  'SoundCloud Go+': require('./soundcloud_gop_soundcloud_logo.png'),
  'Spotify Premium': require('./spotify_premium_logo.png'),
  'Squarespace': require('./squarespace_logo.png'),
  'Strava': require('./strava_logo.png'),
  'Stripe': require('./stripe_logo.png'),
  'Substack': require('./substack_logo.png'),
  'Suno': require('./suno_logo.png'),
  'Supabase': require('./supabase_logo.png'),
  'Surfshark': require('./surfshark_logo.png'),
  'Synthesia': require('./synthesia_logo.png'),
  'Telegram Premium': require('./telegram_premium_telegram_logo.png'),
  'The Economist': require('./the_economist_logo.png'),
  'Tidal': require('./tidal_logo.png'),
  'Tinder': require('./tinder_logo.png'),
  'Todoist': require('./todoist_logo.png'),
  'TradingView': require('./tradingview_logo.png'),
  'Twitch Turbo': require('./twitch_turbo_twitch_logo.png'),
  'Uber One': require('./uber_one_uber_logo.png'),
  'Udemy': require('./udemy_logo.png'),
  'Upstash': require('./upstash_logo.png'),
  'Vercel': require('./vercel_logo.png'),
  'Wall Street Journal': require('./wall_street_journal_logo.png'),
  'Washington Post': require('./washington_post_logo.png'),
  'Webflow': require('./webflow_logo.png'),
  'WHOOP': require('./whoop_logo.png'),
  'Whoop': require('./whoop_logo.png'),
  'Windsurf': require('./windsurf_logo.png'),
  'Wix': require('./wix_logo.png'),
  'WordPress.com': require('./wordpress.com_automattic_logo.png'),
  'World of Warcraft': require('./world_of_warcraft_blizzard_logo.png'),
  'X Premium': require('./x_premium_xai_logo.png'),
  'Xbox Game Pass': require('./xbox_game_pass_microsoft_logo.png'),
  'Xero': require('./xero_logo.png'),
  'YNAB': require('./ynab_logo.png'),
  'YouTube Music': require('./youtube_music_google_logo.png'),
  'YouTube Premium': require('./youtube_premium_google_logo.png'),
  'Zapier': require('./zapier_logo.png'),
  'Zendesk': require('./zendesk_logo.png'),
  'Zoom': require('./zoom_logo.png'),
  'Zwift': require('./zwift_logo.png'),
  // ─── New services: outdoor, weather, sports, fitness ───────────────
  '18Birdies Premium': require('./18birdies_premium_logo.png'),
  'Adidas Training': require('./adidas_training_logo.png'),
  'AllTrails+': require('./alltrails+_logo.png'),
  'Arccos Caddie': require('./arccos_caddie_logo.png'),
  'BetterSleep': require('./bettersleep_logo.png'),
  'Buoyweather Premium': require('./buoyweather_premium_logo.png'),
  'Caltopo Pro': require('./caltopo_pro_logo.png'),
  'Carrot Weather': require('./carrot_weather_logo.png'),
  'Centr': require('./centr_logo.png'),
  'Coros Premium': require('./coros_premium_logo.png'),
  'Down Dog': require('./down_dog_logo.png'),
  'Fatmap Premium': require('./fatmap_premium_logo.png'),
  'Fishbrain Premium': require('./fishbrain_premium_logo.png'),
  'Fitbod': require('./fitbod_logo.png'),
  'Fitbit Premium': require('./fitbit_premium_logo.png'),
  'Flo Premium': require('./flo_premium_logo.png'),
  'Freeletics': require('./freeletics_logo.png'),
  'Gaia GPS Premium': require('./gaia_gps_premium_logo.png'),
  'Garmin Connect+': require('./garmin_connect+_logo.png'),
  'Golfshot Pro': require('./golfshot_pro_logo.png'),
  'Hole19 Premium': require('./hole19_premium_logo.png'),
  'HuntStand Pro': require('./huntstand_pro_logo.png'),
  'iKitesurf Premium': require('./ikitesurf_premium_logo.png'),
  'Insight Timer Premium': require('./insight_timer_premium_logo.png'),
  'JEFIT Elite': require('./jefit_elite_logo.png'),
  'Komoot Premium': require('./komoot_premium_logo.png'),
  'Les Mills+': require('./les_mills+_logo.png'),
  'Magicseaweed Plus': require('./magicseaweed_plus_logo.png'),
  'MapMyRun Premium': require('./mapmyrun_premium_logo.png'),
  'Meditopia Premium': require('./meditopia_premium_logo.png'),
  'MyRadar Pro': require('./myradar_pro_logo.png'),
  'Nike Training Club Premium': require('./nike_training_club_premium_logo.png'),
  'OnTheSnow': require('./onthesnow_logo.png'),
  'onX Backcountry': require('./onx_backcountry_logo.png'),
  'onX Hunt': require('./onx_hunt_logo.png'),
  'OpenSnow Premium': require('./opensnow_premium_logo.png'),
  'PADI Club': require('./padi_club_logo.png'),
  'Peloton App': require('./peloton_app_logo.png'),
  'Playtomic Premium': require('./playtomic_premium_logo.png'),
  'Polar Flow Premium': require('./polar_flow_premium_logo.png'),
  'PredictWind': require('./predictwind_logo.png'),
  'Relive Plus': require('./relive_plus_logo.png'),
  'Rouvy': require('./rouvy_logo.png'),
  'Sleep Cycle Premium': require('./sleep_cycle_premium_logo.png'),
  'Slopes Premium': require('./slopes_premium_logo.png'),
  'Snow-Forecast Premium': require('./snow-forecast_premium_logo.png'),
  'Surfline Premium': require('./surfline_premium_logo.png'),
  'Sweat': require('./sweat_logo.png'),
  'SwingVision Pro': require('./swingvision_pro_logo.png'),
  'TrainerRoad': require('./trainerroad_logo.png'),
  'Wahoo SYNC Premium': require('./wahoo_sync_premium_logo.png'),
  'Weather Underground': require('./weather_underground_logo.png'),
  'Windy Premium': require('./windy_premium_logo.png'),
  'Windy.app Pro': require('./windy.app_pro_logo.png'),
  'Windguru Premium': require('./windguru_premium_logo.png'),
  // ─── Additional logos ──────────────────────────────────────────────
  'OpenAI': require('./openai_logo.png'),
  'OpenAI API': require('./openai_logo.png'),
  'Asana': require('./asana_logo.png'),
  'ClickUp': require('./clickup_logo.png'),
  'Miro': require('./miro_logo.png'),
  'Trello': require('./trello_logo.png'),
  'Jira': require('./jira_logo.png'),
  'Confluence': require('./jira_logo.png'),
  'Calendly': require('./calendly_logo.png'),
  'Loom': require('./loom_logo.png'),
  'Airtable': require('./airtable_logo.png'),
  'Hugging Face': require('./hugging_face_logo.png'),
  'DeepSeek API': require('./deepseek_logo.png'),
  'Obsidian Sync': require('./obsidian_logo.png'),
};

// Build a case-insensitive lookup map once
const lowerLogos: Record<string, ImageSourcePropType> = {};
for (const [key, val] of Object.entries(logos)) {
  lowerLogos[key.toLowerCase()] = val;
}

export function getLogoForProvider(name: string): ImageSourcePropType | null {
  const trimmed = name.trim();
  // 1. Exact match
  if (logos[trimmed]) return logos[trimmed];
  // 2. Case-insensitive match
  const lower = trimmed.toLowerCase();
  if (lowerLogos[lower]) return lowerLogos[lower];
  // 3. Partial match: logo key is a substring of the provider name
  //    e.g. "Claude Pro" → "Claude", "Adobe Creative Cloud All Apps" → "Adobe Creative Cloud"
  for (const [key, val] of Object.entries(lowerLogos)) {
    if (lower.includes(key) || key.includes(lower)) return val;
  }
  return null;
}
